### PR TITLE
Readme for setting up local environment

### PR DESCRIPTION
**Pull request by simransinghal**
Issue #69 

Documented the steps for setting up local environment.

### CODE REVIEW

**Comment by GeorgLink** [comment]
Were you successful in following the steps? 
Any thoughts on enhancing the instructions with screenshots?

**Comment by simransinghal** [comment]
@GeorgLink I have successfully tested these steps twice.
Adding screenshots seems to be a good idea to me.

**Comment by simransinghal** [comment]
@GeorgLink But some of the commands or most of the commands are very direct, So adding screen-shot of each command may not be a good idea.

We can also make a installation video?

After the review of everyone, we can go ahead with the common suggestion.
@andyl

**Comment by GeorgLink** [comment]
Thank you.
A video would be nice. Do you have the time to record one?

**Comment by simransinghal** [comment]
@GeorgLink I'll record the one after once everyone review the README.

**Comment by GeorgLink** [comment]
​Good plan.

**Comment by simransinghal** [comment]
@andyl

**Comment by GeorgLink** [comment]
@malvikarao I know you wanted to set up a local Bugmark instance. Do these instruction make sense to you?

**Comment by malvikarao** [comment]
I will know if they make sense once I try them. The part on "testing", "host web access", and "online collaboration" does not read well to me.

**Comment by snehasi** [comment]
Hi @GeorgLink and @andyl 

What is the ansible version needed for the playbook? It's not mentioned under roles in  development.yml. I'm getting some errors possibly due to the ansible version, I'm using ansible==2.1.2.

```
ERROR! the role 'Vars/predicates' was not found in /home/sneha/src/exchange/script/dev/provision/playbook/roles:/home/sneha/src/exchange/script/dev/provision/playbook:/home/sneha/util/x-ansible/roles

The error appears to have been in '/home/sneha/src/exchange/script/dev/provision/playbook/development.yml': line 15, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - Vars/predicates
      ^ here
```

**Comment by andyl** [comment]
@snehasi I'm using Ansible 2.3.2.0

I'll do an end-to-end test now, following the instructions and verifying that everything works.

I did this a couple weeks ago - but practice makes perfect.

I'm going to close this PR - @snehasi if you want to discuss this more hit me up via email, slack or bugmark_dev.

:-)

**Pull request closed without merging**
